/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorajava;

/**
 *
 * @author Ricar
 */
public class Formulario_calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_calculadora
     */
    public Formulario_calculadora() {
        initComponents();
    }
    
    Double valor1, valor2;
    String sinal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_painel = new javax.swing.JPanel();
        lb_calculadora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_cinco = new javax.swing.JButton();
        bt_zero = new javax.swing.JButton();
        bt_ponto = new javax.swing.JButton();
        bt_quatro = new javax.swing.JButton();
        bt_menos = new javax.swing.JButton();
        bt_dividido = new javax.swing.JButton();
        bt_c = new javax.swing.JButton();
        bt_dois = new javax.swing.JButton();
        bt_tres = new javax.swing.JButton();
        bt_um = new javax.swing.JButton();
        bt_seis = new javax.swing.JButton();
        bt_vezes = new javax.swing.JButton();
        tb_resultado = new javax.swing.JTextField();
        bt_oito = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_sete = new javax.swing.JButton();
        bt_mais = new javax.swing.JButton();
        bt_igual = new javax.swing.JButton();
        bt_ce = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_painel.setBackground(new java.awt.Color(102, 102, 102));

        lb_calculadora.setBackground(new java.awt.Color(255, 153, 255));
        lb_calculadora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lb_calculadora.setForeground(new java.awt.Color(255, 255, 255));
        lb_calculadora.setText("CALCULADORA JAVA");

        javax.swing.GroupLayout pn_painelLayout = new javax.swing.GroupLayout(pn_painel);
        pn_painel.setLayout(pn_painelLayout);
        pn_painelLayout.setHorizontalGroup(
            pn_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_painelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lb_calculadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_painelLayout.setVerticalGroup(
            pn_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_painelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_calculadora)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bt_cinco.setBackground(new java.awt.Color(51, 51, 51));
        bt_cinco.setForeground(new java.awt.Color(255, 255, 255));
        bt_cinco.setText("5");
        bt_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cincoActionPerformed(evt);
            }
        });

        bt_zero.setBackground(new java.awt.Color(51, 51, 51));
        bt_zero.setForeground(new java.awt.Color(255, 255, 255));
        bt_zero.setText("0");
        bt_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_zeroActionPerformed(evt);
            }
        });

        bt_ponto.setBackground(new java.awt.Color(51, 51, 51));
        bt_ponto.setForeground(new java.awt.Color(255, 255, 255));
        bt_ponto.setText(".");
        bt_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pontoActionPerformed(evt);
            }
        });

        bt_quatro.setBackground(new java.awt.Color(51, 51, 51));
        bt_quatro.setForeground(new java.awt.Color(255, 255, 255));
        bt_quatro.setText("4");
        bt_quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quatroActionPerformed(evt);
            }
        });

        bt_menos.setBackground(new java.awt.Color(51, 51, 51));
        bt_menos.setForeground(new java.awt.Color(255, 255, 255));
        bt_menos.setText("-");
        bt_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menosActionPerformed(evt);
            }
        });

        bt_dividido.setBackground(new java.awt.Color(51, 51, 51));
        bt_dividido.setForeground(new java.awt.Color(255, 255, 255));
        bt_dividido.setText("÷");
        bt_dividido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divididoActionPerformed(evt);
            }
        });

        bt_c.setBackground(new java.awt.Color(51, 51, 51));
        bt_c.setForeground(new java.awt.Color(255, 255, 255));
        bt_c.setText("C");
        bt_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cActionPerformed(evt);
            }
        });

        bt_dois.setBackground(new java.awt.Color(51, 51, 51));
        bt_dois.setForeground(new java.awt.Color(255, 255, 255));
        bt_dois.setText("2");
        bt_dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_doisActionPerformed(evt);
            }
        });

        bt_tres.setBackground(new java.awt.Color(51, 51, 51));
        bt_tres.setForeground(new java.awt.Color(255, 255, 255));
        bt_tres.setText("3");
        bt_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tresActionPerformed(evt);
            }
        });

        bt_um.setBackground(new java.awt.Color(51, 51, 51));
        bt_um.setForeground(new java.awt.Color(255, 255, 255));
        bt_um.setText("1");
        bt_um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_umActionPerformed(evt);
            }
        });

        bt_seis.setBackground(new java.awt.Color(51, 51, 51));
        bt_seis.setForeground(new java.awt.Color(255, 255, 255));
        bt_seis.setText("6");
        bt_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seisActionPerformed(evt);
            }
        });

        bt_vezes.setBackground(new java.awt.Color(51, 51, 51));
        bt_vezes.setForeground(new java.awt.Color(255, 255, 255));
        bt_vezes.setText("x");
        bt_vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_vezesActionPerformed(evt);
            }
        });

        tb_resultado.setBackground(new java.awt.Color(204, 204, 204));

        bt_oito.setBackground(new java.awt.Color(51, 51, 51));
        bt_oito.setForeground(new java.awt.Color(255, 255, 255));
        bt_oito.setText("8");
        bt_oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_oitoActionPerformed(evt);
            }
        });

        bt_9.setBackground(new java.awt.Color(51, 51, 51));
        bt_9.setForeground(new java.awt.Color(255, 255, 255));
        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        bt_sete.setBackground(new java.awt.Color(51, 51, 51));
        bt_sete.setForeground(new java.awt.Color(255, 255, 255));
        bt_sete.setText("7");
        bt_sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_seteActionPerformed(evt);
            }
        });

        bt_mais.setBackground(new java.awt.Color(51, 51, 51));
        bt_mais.setForeground(new java.awt.Color(255, 255, 255));
        bt_mais.setText("+");
        bt_mais.setToolTipText("");
        bt_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_maisActionPerformed(evt);
            }
        });

        bt_igual.setBackground(new java.awt.Color(51, 51, 51));
        bt_igual.setForeground(new java.awt.Color(255, 255, 255));
        bt_igual.setText("=");
        bt_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_igualActionPerformed(evt);
            }
        });

        bt_ce.setBackground(new java.awt.Color(51, 51, 51));
        bt_ce.setForeground(new java.awt.Color(255, 255, 255));
        bt_ce.setText("CE");
        bt_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bt_vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_dividido, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(tb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_oito, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_mais, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_sete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_dois, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_um, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_ponto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_dividido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(bt_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pn_painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_zeroActionPerformed
        // TODO add your handling code here:
        
        tb_resultado.setText(tb_resultado.getText()+"0");
    }//GEN-LAST:event_bt_zeroActionPerformed

    private void bt_umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_umActionPerformed
        // TODO add your handling code here:
        
        tb_resultado.setText(tb_resultado.getText()+"1");
    }//GEN-LAST:event_bt_umActionPerformed

    private void bt_doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_doisActionPerformed
        // TODO add your handling code here:
        
        tb_resultado.setText(tb_resultado.getText()+"2");
    }//GEN-LAST:event_bt_doisActionPerformed

    private void bt_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tresActionPerformed
        // TODO add your handling code here:
        
        tb_resultado.setText(tb_resultado.getText()+"3");
    }//GEN-LAST:event_bt_tresActionPerformed

    private void bt_quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quatroActionPerformed
        // TODO add your handling code here:
        
        tb_resultado.setText(tb_resultado.getText()+"4");
    }//GEN-LAST:event_bt_quatroActionPerformed

    private void bt_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cincoActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+"5");
    }//GEN-LAST:event_bt_cincoActionPerformed

    private void bt_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seisActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+"6");
    }//GEN-LAST:event_bt_seisActionPerformed

    private void bt_seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_seteActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+"7");
    }//GEN-LAST:event_bt_seteActionPerformed

    private void bt_oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_oitoActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+"8");
    }//GEN-LAST:event_bt_oitoActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+"9");
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pontoActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText(tb_resultado.getText()+".");
    }//GEN-LAST:event_bt_pontoActionPerformed

    private void bt_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ceActionPerformed
        // TODO add your handling code here:
        
         tb_resultado.setText("");
    }//GEN-LAST:event_bt_ceActionPerformed

    private void bt_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_maisActionPerformed
        // TODO add your handling code here:
                
        valor1 = Double.parseDouble(tb_resultado.getText());
        tb_resultado.setText("");
        sinal = "soma";
    }//GEN-LAST:event_bt_maisActionPerformed

    private void bt_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_igualActionPerformed
        // TODO add your handling code here:
        
        valor2 = Double.parseDouble(tb_resultado.getText());
        if(sinal == "soma"){
            tb_resultado.setText(String.valueOf(valor1 + valor2));
        }
        
        else if(sinal == "menos"){
            tb_resultado.setText(String.valueOf(valor1 - valor2));
        }
        
        else if(sinal == "vezes"){
            tb_resultado.setText(String.valueOf(valor1 * valor2));
        }
        
        else if(sinal == "divisao"){
            tb_resultado.setText(String.valueOf(valor1 / valor2));
        }
        
    }//GEN-LAST:event_bt_igualActionPerformed

    private void bt_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menosActionPerformed
        // TODO add your handling code here:
        
        valor1 = Double.parseDouble(tb_resultado.getText());
        tb_resultado.setText("");
        sinal = "menos";
    }//GEN-LAST:event_bt_menosActionPerformed

    private void bt_vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_vezesActionPerformed
        // TODO add your handling code here:
        
        valor1 = Double.parseDouble(tb_resultado.getText());
        tb_resultado.setText("");
        sinal = "vezes";
    }//GEN-LAST:event_bt_vezesActionPerformed

    private void bt_divididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divididoActionPerformed
        // TODO add your handling code here:
        
        valor1 = Double.parseDouble(tb_resultado.getText());
        tb_resultado.setText("");
        sinal = "divisao";
    }//GEN-LAST:event_bt_divididoActionPerformed

    private void bt_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cActionPerformed
        // TODO add your handling code here:
        
        valor1 = null;
        valor2 = null;
        tb_resultado.setText("");
    }//GEN-LAST:event_bt_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_c;
    private javax.swing.JButton bt_ce;
    private javax.swing.JButton bt_cinco;
    private javax.swing.JButton bt_dividido;
    private javax.swing.JButton bt_dois;
    private javax.swing.JButton bt_igual;
    private javax.swing.JButton bt_mais;
    private javax.swing.JButton bt_menos;
    private javax.swing.JButton bt_oito;
    private javax.swing.JButton bt_ponto;
    private javax.swing.JButton bt_quatro;
    private javax.swing.JButton bt_seis;
    private javax.swing.JButton bt_sete;
    private javax.swing.JButton bt_tres;
    private javax.swing.JButton bt_um;
    private javax.swing.JButton bt_vezes;
    private javax.swing.JButton bt_zero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_calculadora;
    private javax.swing.JPanel pn_painel;
    private javax.swing.JTextField tb_resultado;
    // End of variables declaration//GEN-END:variables
}
