/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogodavelhajava;

/**
 *
 * @author ricardo.vieira
 */
public class Jogo extends javax.swing.JFrame {
public boolean player1=true;
public boolean player2=true;
public int contadorPosicao=0;
public int contaum=0, contadois=0;
int valor;
public String linha1, linha2, linha3, coluna1, coluna2, coluna3, diagonal1, diagonal2;
String [] [] posicaovetor=new String [3] [3];


        
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btReiniciar = new javax.swing.JButton();
        txtVisor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt1.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt1.setToolTipText("");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt2.setToolTipText("");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt3.setToolTipText("");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt6.setToolTipText("");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt4.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt4.setToolTipText("");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt5.setToolTipText("");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt9.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt9.setToolTipText("");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt7.setToolTipText("");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setFont(new java.awt.Font("Arial", 1, 90)); // NOI18N
        bt8.setToolTipText("");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        btReiniciar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btReiniciar.setText("REINICIAR");
        btReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarActionPerformed(evt);
            }
        });

        txtVisor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtVisor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVisor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void limparVetor(){
        for(contaum=0; contaum<3; contaum++){
            for(contadois=0; contadois<3; contadois++){
                posicaovetor [contaum] [contadois] = "";
            }
        }
    }
    
    
    public void verificarJogador(){
        if(player1 && player2){
            this.valor=1;
            player1=false;
            player2=true;
            txtVisor.setText("Agora é a vez do O");
                       
        }
        
        else if(player1 && player2 == false){
            this.valor=1;
            player1=false;
            player2=true;
            txtVisor.setText("Agora é a vez do O");
        }
        
        else{
            this.valor=2;
            player1=true;
            player2=false;
            txtVisor.setText("Agora é a vez do X");
        }
    }
    
    public void desativaBotoes(){
        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
        bt5.setEnabled(false);
        bt6.setEnabled(false);
        bt7.setEnabled(false);
        bt8.setEnabled(false);
        bt9.setEnabled(false);
              
    }
    
    public void verificaEmpate(){
        contadorPosicao = 0;
        for(contaum=0; contaum<3; contaum++){
            for(contadois=0; contadois<3; contadois++){
                if(posicaovetor [contaum] [contadois] == "x" | posicaovetor [contaum] [contadois] == "o"){
                    contadorPosicao += 1;
                }
            }
        }
    }
    public void verificaVencedor(){
        linha1 = posicaovetor [0] [0] + posicaovetor [0] [1] + posicaovetor [0] [2];
        linha2 = posicaovetor [1] [0] + posicaovetor [1] [1] + posicaovetor [1] [2];
        linha3 = posicaovetor [2] [0] + posicaovetor [2] [1] + posicaovetor [2] [2];
        
        coluna1 = posicaovetor [0] [0] + posicaovetor [1] [0] + posicaovetor [2] [0];
        coluna2 = posicaovetor [0] [1] + posicaovetor [1] [1] + posicaovetor [2] [1];
        coluna3 = posicaovetor [0] [2] + posicaovetor [1] [2] + posicaovetor [2] [2];
        
        diagonal1 = posicaovetor [0] [0] + posicaovetor [1] [1] + posicaovetor [2] [2];
        diagonal2 = posicaovetor [0] [2] + posicaovetor [1] [1] + posicaovetor [2] [0];
        
        if(linha1.equals("xxx") | linha2.equals("xxx") | linha3.equals("xxx") | linha3.equals("xxx") | coluna1.equals("xxx") | coluna2.equals("xxx") | coluna3.equals("xxx") | diagonal1.equals("xxx") | diagonal2.equals("xxx")){
            txtVisor.setText("X Venceu!");
            desativaBotoes();
        }
        
        else if(linha1.equals("ooo") | linha2.equals("ooo") | linha3.equals("ooo") | linha3.equals("ooo") | coluna1.equals("ooo") | coluna2.equals("ooo") | coluna3.equals("ooo") | diagonal1.equals("ooo") | diagonal2.equals("ooo")){ 
            txtVisor.setText("O Venceu!");
            desativaBotoes();
        }
        
        else if (contadorPosicao == 9){            
             txtVisor.setText("Velha!");     
    }
        
        
    }
    
    
    
    
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        verificarJogador();
        if(valor==1){
        bt1.setText("X");
        posicaovetor[0][0] = "x";
        }
        
        else{
        bt1.setText("O");
        posicaovetor[0][0] = "o";
        }
        
        bt1.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
        
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
         verificarJogador();
        if(valor==1){
        bt2.setText("X");
        posicaovetor[0][1] = "x";
        }
        
        else{
        bt2.setText("O");
        posicaovetor[0][1] = "o";
        }
        
        bt2.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
          verificarJogador();
        if(valor==1){
        bt3.setText("X");
        posicaovetor[0][2] = "x";
        }
        
        else{
        bt3.setText("O");
        posicaovetor[0][2] = "o";
        }
        
        bt3.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
          verificarJogador();
        if(valor==1){
        bt4.setText("X");
        posicaovetor[1][0] = "x";
        }
        
        else{
        bt4.setText("O");
        posicaovetor[1][0] = "o";
        }
        
        bt4.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        verificarJogador();
        if(valor==1){
        bt5.setText("X");
        posicaovetor[1][1] = "x";
        }
        
        else{
        bt5.setText("O");
        posicaovetor[1][1] = "o";
        }
        
        bt5.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
         verificarJogador();
        if(valor==1){
        bt6.setText("X");
        posicaovetor[1][2] = "x";
        }
        
        else{
        bt6.setText("O");
        posicaovetor[1][2] = "o";
        }
        
        bt6.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
          verificarJogador();
        if(valor==1){
        bt7.setText("X");
        posicaovetor[2][0] = "x";
        }
        
        else{
        bt7.setText("O");
        posicaovetor[2][0] = "o";
        }
        
        bt7.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
          verificarJogador();
        if(valor==1){
        bt8.setText("X");
        posicaovetor[2][1] = "x";
        }
        
        else{
        bt8.setText("O");
        posicaovetor[2][1] = "o";
        }
        
        bt8.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
          verificarJogador();
        if(valor==1){
        bt9.setText("X");
        posicaovetor[2][2] = "x";
        }
        
        else{
        bt9.setText("O");
        posicaovetor[2][2] = "o";
        }
        
        bt9.setEnabled(false);
        verificaEmpate();
        verificaVencedor();
        
    }//GEN-LAST:event_bt9ActionPerformed

    private void btReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarActionPerformed
        bt1.setText("");
        bt1.setEnabled(true);
        
        bt2.setText("");
        bt2.setEnabled(true);
        
        bt3.setText("");
        bt3.setEnabled(true);
        
        bt4.setText("");
        bt4.setEnabled(true);
        
        bt5.setText("");
        bt5.setEnabled(true);
        
        bt6.setText("");
        bt6.setEnabled(true);
        
        bt7.setText("");
        bt7.setEnabled(true);
        
        bt8.setText("");
        bt8.setEnabled(true);
        
        bt9.setText("");
        bt9.setEnabled(true);
        
        limparVetor();
        txtVisor.setText("");
        player1 = true;
        player2 = true;
    }//GEN-LAST:event_btReiniciarActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btReiniciar;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables
}
